<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Auralith.Updater</AssemblyName>
    <RootNamespace>Auralith.Updater</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auralith.Update\Auralith.Update.csproj" />
  </ItemGroup>
</Project>
