<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Auralith.Platform.Windows</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auralith.Core\Auralith.Core.csproj" />
  </ItemGroup>
</Project>

