/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutputRouteImport } from './routes/output'
import { Route as SourceIdRouteImport } from './routes/source.$id'
import { Route as ApiAuralithImageRouteImport } from './routes/api/auralith/image'
import { Route as ApiAuralithLiveRouteImport } from './routes/api/auralith/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputRoute = OutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceIdRoute = SourceIdRouteImport.update({
  id: '/source/$id',
  path: '/source/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuralithImageRoute = ApiAuralithImageRouteImport.update({
  id: '/api/auralith/image',
  path: '/api/auralith/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuralithLiveRoute = ApiAuralithLiveRouteImport.update({
  id: '/api/auralith/live',
  path: '/api/auralith/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/output': typeof OutputRoute
  '/source/$id': typeof SourceIdRoute
  '/api/auralith/image': typeof ApiAuralithImageRoute
  '/api/auralith/live': typeof ApiAuralithLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/output': typeof OutputRoute
  '/source/$id': typeof SourceIdRoute
  '/api/auralith/image': typeof ApiAuralithImageRoute
  '/api/auralith/live': typeof ApiAuralithLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/output': typeof OutputRoute
  '/source/$id': typeof SourceIdRoute
  '/api/auralith/image': typeof ApiAuralithImageRoute
  '/api/auralith/live': typeof ApiAuralithLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/output'
    | '/source/$id'
    | '/api/auralith/image'
    | '/api/auralith/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/output'
    | '/source/$id'
    | '/api/auralith/image'
    | '/api/auralith/live'
  id:
    | '__root__'
    | '/'
    | '/output'
    | '/source/$id'
    | '/api/auralith/image'
    | '/api/auralith/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutputRoute: typeof OutputRoute
  SourceIdRoute: typeof SourceIdRoute
  ApiAuralithImageRoute: typeof ApiAuralithImageRoute
  ApiAuralithLiveRoute: typeof ApiAuralithLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output': {
      id: '/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof OutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source/$id': {
      id: '/source/$id'
      path: '/source/$id'
      fullPath: '/source/$id'
      preLoaderRoute: typeof SourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auralith/image': {
      id: '/api/auralith/image'
      path: '/api/auralith/image'
      fullPath: '/api/auralith/image'
      preLoaderRoute: typeof ApiAuralithImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auralith/live': {
      id: '/api/auralith/live'
      path: '/api/auralith/live'
      fullPath: '/api/auralith/live'
      preLoaderRoute: typeof ApiAuralithLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutputRoute: OutputRoute,
  SourceIdRoute: SourceIdRoute,
  ApiAuralithImageRoute: ApiAuralithImageRoute,
  ApiAuralithLiveRoute: ApiAuralithLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
